### ISSUE TITLE
hass.components.configurator is deprecated

### ISSUE THREAD

**Issue by yx37055** [alexmohr/media_player.sony#39]
Guten morgen Alex !
Hopefully you still provide support for your development.

I'm new to HA and trying to get my Sony bluray player working using your code.
(I precise that remote control works using php code based on IRCC protocol. So player is OK)

Integration seems OK as I see it in the list.
But while adding lines to configuration.yaml nothing appears. No configuration is initiated.
Maybe I'm missing something stupid.

When looking to the log, I see:
----------------------------------
2024-08-03 10:40:00.067 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sony which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-03 10:40:09.042 INFO (MainThread) [homeassistant.components.media_player] Setting up sony.media_player
2024-08-03 10:40:09.108 WARNING (SyncWorker_3) [homeassistant.helpers.frame] Detected that custom integration 'sony' accesses hass.components.configurator. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from configurator directly at custom_components/sony/media_player.py, line 130: configurator = hass.components.configurator, please report it to the author of the 'sony' custom integration----------------------------------

Any help will be greatly appreciated.
Thanks in advance !

**Comment by alexmohr** [comment]
Hi,

I'm not really maintaining this component at the moment because I don't have the time to do so and I'm not using the integration myself anymore. 
I do accept pull requests though. 
As 2024.9 is not released yet the configuration should still work until then. It could also be the case that you particular device is not supported

**Comment by yx37055** [comment]
Hi,
Thanks a lot for your quick reply and still accepting requests !!!
FYI, my player is a SONY UBP-X1100ES (UHD player).

I made progress as now, an entity is appearing with the name I gave in the configuration.yaml.
I've even been able to complete the pairing with the PIN code.
I'm now stuck as I got no clue how to send a command to the player.

Should there be a device created automatically ? Should I create it myself ?
Should I create something manually in the dashboard ?

Not sure if that is important but when opending settings of the entity, I got following message: "This entity ('media_player.ubp_x1100es') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail."

Fabrice

**Comment by alexmohr** [comment]
Once you've been able to configure the pin it should show up in devices in the home assistant settings and a player entity should be visible which you can add to Lovelace. If it doesn't the configuration failed, maybe there is something about this in the home assistant log. 
In any case you have to add the device manually to a dashboard.
The main issue is that each of these devices works a bit differently and the API is not publicly documented.

**Comment by yx37055** [comment]
OK I see.
Then I'll look at the code and try to adapt it until a device is reated.
Thanks for the advice.

I've also seen that a sony.conf file has been generated with all the possible commands it seems.

Thanks again Alexander. Very appreciated !
Enjoy olympics in case you follow them :-)

**Comment by totallydifferent** [comment]
Hi Alex and Fabrice,

Appreciate your work with this. I understand you're not actively maintaining this code anymore Alex.

I'm trying to get this working for my UBP-800M2 but there seem to be some issues with some deprecated code:

Platform error: media_player - cannot import name 'save_json' from 'homeassistant.util.json' (/usr/src/homeassistant/homeassistant/util/json.py)

From some quick searching I found that the current code uses save_json from homeassistant.util.json module. This was deprecated and stopped working in Home Assistant 2022.4, it should be updated to use homeassistant.helpers.json module instead.

Also had these errors:
SUPPORT_PLAY_MEDIA was used from sony, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.PLAY_MEDIA instead, please report it to the author of the 'sony' custom integration
SUPPORT_STOP was used from sony, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.STOP instead, please report it to the author of the 'sony' custom integration
SUPPORT_VOLUME_MUTE was used from sony, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_MUTE instead, please report it to the author of the 'sony' custom integration
SUPPORT_VOLUME_STEP was used from sony, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_STEP instead, please report it to the author of the 'sony' custom integration
SUPPORT_VOLUME_SET was used from sony, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_SET instead, please report it to the author of the 'sony' custom integration

And this:
Detected blocking call to import_module with args ('custom_components.sony.media_player',) inside the event loop by integration 'homeassistant' at homeassistant/components/homeassistant/__init__.py, line 350

I don't have familiarity with HA to be able to help just yet - but thought I would share this here to see if anyone else has managed to work around this. Will keep chipping away and update if I have a solution.

Thanks again for all your work!

**Comment by alexmohr** [comment]
There isn't really a workaround for this. The component needs a major overhaul to work again, as it was not really updated for a long time now. It's using things that have been removed from home assistant.
It might be worth to merge the changes done by @albaintor in the version by @dilruacs because they reworked the configuration process and might not need the json dependency anymore. 

I don't have spare time to spend on this project currently but pull requests are appreciated, as long as they are properly tested.

**Comment by yx37055** [comment]
Thanks again, Alex. I'll have a look on dilruacs' work.

@totallydifferent in spite of my efforts, I've not been able to get it working on HA.
So I'm using an alternative based on a french box called eedomus.
But if you are more successful than me, I'd be really interested ! :-)

**Comment by totallydifferent** [comment]
@yx37055 doesn't seem too promising for IP control for my X800M2 unfortunately. Its the end of the road for me.

here is more info: https://www.remotecentral.com/cgi-bin/mboard/rc-custom/thread.cgi?42362

@alexmohr thanks for the info - and i did try that and it looked more promising until I identified the issue with my particular model of player.

thank you both and have a great weekend!

**Comment by yx37055** [comment]
Just a quick email to inform you that dilruacs' version worked perfectly for me. At least for the installation part.
@totallydifferent I'm sorry for you as it seems your model is not compatible.

But I'm now stuck as I got no clue where to put the code indicated to send a command to the player:
"service: remote.send_command
data:
  command: Up
target:
  entity_id: remote.sony_remote"

**Comment by yx37055** [comment]
Final update:
I finally found where and how to attach the code indicated by @dilruacs. And now everything is working !!!
It is really annoying as it seems every new HA version is breaking what has been developed or documented for previous version.
I guess that is the compromise to see regular new features on the product.

Anyway, thanks again Alex.

**Comment by surdu** [comment]
@yx37055, could you please share a fork where you patched the code to work? Better yet, could you open a PR on this repo?

Thank you!
